# Generated by Django 3.1.2 on 2020-11-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1000)),
                ('imageOne', models.CharField(max_length=1000)),
                ('imageTwo', models.CharField(max_length=1000)),
                ('imageThree', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('procedure', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentalFest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOne', models.CharField(max_length=1000)),
                ('imageTwo', models.CharField(max_length=1000)),
                ('imageThree', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('department', models.ManyToManyField(blank=True, related_name='departmentofdepartmentalfests', to='departmentalfests.Department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='eventofdepartment', to='departmentalfests.Event'),
        ),
    ]
