# Generated by Django 3.1.2 on 2020-11-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentalfests', '0003_auto_20201103_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
