# Generated by Django 3.1.2 on 2020-11-21 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('departmentalfests', '0004_auto_20201120_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='procedure',
            new_name='rules',
        ),
        migrations.AddField(
            model_name='event',
            name='eventhead',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='registrationform',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
