# Generated by Django 3.1.2 on 2020-11-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20201102_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='door',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=7),
        ),
    ]
