# Generated by Django 3.1.2 on 2020-11-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20201103_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sportlist',
            name='imageOne',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sportlist',
            name='imageTwo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
