# Generated by Django 3.1.2 on 2020-11-04 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0005_auto_20201104_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('registration', models.TextField(blank=True)),
                ('howtoplay', models.TextField(blank=True)),
                ('sporthead', models.CharField(max_length=64)),
                ('fees', models.IntegerField()),
                ('door', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Sportlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOne', models.ImageField(blank=True, upload_to='')),
                ('imageTwo', models.ImageField(blank=True, upload_to='')),
                ('quoteOne', models.CharField(max_length=200)),
                ('quoteTwo', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sports', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sportsofsportlist', to='sports.sport')),
            ],
        ),
    ]
