# Generated by Django 3.1.2 on 2020-11-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_sport_sportlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sporthead',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sportlist',
            name='quoteOne',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='sportlist',
            name='quoteTwo',
            field=models.CharField(max_length=2000),
        ),
    ]
