# Generated by Django 3.1.2 on 2020-11-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_auto_20201123_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='registration',
            field=models.CharField(max_length=1000),
        ),
        migrations.RemoveField(
            model_name='sportlist',
            name='sports',
        ),
        migrations.AddField(
            model_name='sportlist',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='sportsofsportlist', to='sports.Sport'),
        ),
    ]
