# Generated by Django 3.1.2 on 2020-11-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0002_auto_20201031_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='dayImageOne',
            new_name='imageOne',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='dayImageThree',
            new_name='imageThree',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='dayImageTwo',
            new_name='imageTwo',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='daysImageOne',
            new_name='imageOne',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='daysImageThree',
            new_name='imageThree',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='daysImageTwo',
            new_name='imageTwo',
        ),
    ]
