# Generated by Django 3.1.2 on 2020-11-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0004_auto_20201102_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trialimage',
            field=models.ImageField(blank=True, height_field=100, upload_to='', width_field=100),
        ),
    ]
