# Generated by Django 3.1.2 on 2020-11-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0005_event_trialimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trialimage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
