# Generated by Django 3.1.2 on 2020-11-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0006_auto_20201103_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='imageOne',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='day',
            name='imageThree',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='day',
            name='imageTwo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='days',
            name='imageOne',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='days',
            name='imageThree',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='days',
            name='imageTwo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
