# Generated by Django 3.1.2 on 2020-11-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0008_auto_20201120_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registrationform',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
